
pipelines:
  default:
    - step: 
        name: Build Front end
        image: node:10.15.0
        script:
          - cd teach-me-ui
          - npm install
          - npm test -- --coverage --coverageDirectory=output/coverage/jest  
          - tar -czvf coverage.tar.gz output/coverage/jest
          - npm run build
          - mkdir packaged
          - tar -czvf packaged/package-${BITBUCKET_BUILD_NUMBER}.tar.gz -C build . 
          - cd ..
        artifacts:
          - teach-me-ui/packaged/**
          - teach-me-ui/coverage.tar.gz

  branches:
    TMFED-33-configure-automatic-redirects-t:
    - step: 
        name: Build Front end
        image: node:10.15.0
        script:
          - cd teach-me-ui
          - npm install
          - npm test -- --coverage --coverageDirectory=output/coverage/jest  
          - tar -czvf coverage.tar.gz output/coverage/jest
          - npm run build
          - mkdir packaged
          - tar -czvf packaged/package-${BITBUCKET_BUILD_NUMBER}.tar.gz -C build .
          - cd ..
        artifacts:
          - teach-me-ui/packaged/**
          - teach-me-ui/coverage.tar.gz

    - step:
          name: Deploy to Heroku
          image: node:10.15.0
          deployment: test
          script:
            - tar --exclude='./node_modules' --exclude='./build' -czvf application-${BITBUCKET_BUILD_NUMBER}.tar.gz -C teach-me-ui .
            - pipe: atlassian/heroku-deploy:1.1.2
              variables:
                HEROKU_API_KEY: $HEROKU_API_KEY
                HEROKU_APP_NAME: $HEROKU_APP_UI
                ZIP_FILE: "application-${BITBUCKET_BUILD_NUMBER}.tar.gz"
