import { RequestState } from '../types';

export const SET_COLLEAGUE_REQUESTS = 'SET_COLLEAGUE_REQUESTS';
export const DEEP_PROFILE_DATA = 'FETCHED_DEEP_PROFILE_DATA';

export const ADD_COLLEAGUE_STARTED = 'ADD_COLLEAGUE_STARTED';
export const ADD_COLLEAGUE_REJECTED = 'ADD_COLLEAGUE_REJECTED';
export const ADD_COLLEAGUE_RESOLVED = 'ADD_COLLEAGUE_RESOLVED';

export const FETCH_DEEP_PROFILE_STARTED = 'FETCH_DEEP_PROFILE_STARTED';
export const FETCH_DEEP_PROFILE_REJECTED = 'FETCH_DEEP_PROFILE_REJECTED';
export const FETCH_DEEP_PROFILE_RESOLVED = 'FETCH_DEEP_PROFILE_RESOLVED';

export const REMOVE_COLLEAGUE_STARTED = 'REMOVE_COLLEAGUE_STARTED';
export const REMOVE_COLLEAGUE_REJECTED = 'REMOVE_COLLEAGUE_REJECTED';
export const REMOVE_COLLEAGUE_RESOLVED = 'REMOVE_COLLEAGUE_RESOLVED';

export const ACCEPT_COLLEAGUE_STARTED = 'ACCEPT_COLLEAGUE_STARTED';
export const ACCEPT_COLLEAGUE_REJECTED = 'ACCEPT_COLLEAGUE_REJECTED';
export const ACCEPT_COLLEAGUE_RESOLVED = 'ACCEPT_COLLEAGUE_RESOLVED';

export const DECLINE_COLLEAGUE_STARTED = 'DECLINE_COLLEAGUE_STARTED';
export const DECLINE_COLLEAGUE_REJECTED = 'DECLINE_COLLEAGUE_REJECTED';
export const DECLINE_COLLEAGUE_RESOLVED = 'DECLINE_COLLEAGUE_RESOLVED';

export const UNCOLLEAGUE_STARTED = 'UNCOLLEAGUE_STARTED';
export const UNCOLLEAGUE_REJECTED = 'UNCOLLEAGUE_REJECTED';
export const UNCOLLEAGUE_RESOLVED = 'UNCOLLEAGUE_RESOLVED';

export const FETCH_COLLEAGUES_STARTED = 'FETCH_COLLEAGUES_STARTED';
export const FETCH_COLLEAGUES_REJECTED = 'FETCH_COLLEAGUES_REJECTED';
export const FETCH_COLLEAGUES_RESOLVED = 'FETCH_COLLEAGUES_RESOLVED';
export const FETCHED_COLLEAGUES = 'FETCHED_COLLEAGUES';

export const FETCH_COLLEAGUE_REQUESTS_STARTED =
  'FETCH_COLLEAGUE_REQUESTS_STARTED';
export const FETCH_COLLEAGUE_REQUESTS_REJECTED =
  'FETCH_COLLEAGUE_REQUESTS_REJECTED';
export const FETCH_COLLEAGUE_REQUESTS_RESOLVED =
  'FETCH_COLLEAGUE_REQUESTS_RESOLVED';
export const FETCHED_COLLEAGUE_REQUESTS = 'FETCHED_COLLEAGUE_REQUESTS';

export const IS_COLLEAGUE = 'IS_COLLEAGUE';
export const PENDING_REQUEST = 'PENDING_REQUEST';
export const AWAITING_REQUEST_ACTION = 'AWAITING_REQUEST_ACTION';
export const NOT_COLLEAGUES = 'NOT_COLLEAGUES';

export const ADD_COLLEAGUE = 'ADD_COLLEAGUE';
export const CANCEL_REQUEST = 'CANCEL_REQUEST';
export const ACCEPT_REQUEST = 'ACCEPT_REQUEST';
export const DECLINE_REQUEST = 'DECLINE_REQUEST';
export const UNCOLLEAGUE = 'UNCOLLEAGUE';

export const COLLEAGUE_ACTION = 'COLLEAGUE_ACTION';
export const REQUEST_COLLEAGUE_ACTION = 'REQUEST_COLLEAGUE_ACTION';

export const requestState: RequestState = {
  status: 'resolved'
};
