export const REQUEST_ADD_COLLEAGUE = 'REQUEST_ADD_COLLEAGUE';
export const ADD_COLLEAGUE = 'ADD_COLLEAGUE';

export const PROFILE_DATA = 'PROFILE_DATA';
export const GET_PROFILE_DATA = 'GET_PROFILE_DATA';
