import { EditProfileState } from '../types';

export const GET_USER_DETAILS = 'GET_USER_DETAILS';
export const GET_USER_DETAILS_REQUEST = 'GET_USER_DETAILS_REQUEST';
export const UPDATE_PASSWORD = 'UPDATE_PASSWORD';
export const UPDATE_PASSWORD_REQUEST = 'UPDATE_PASSWORD_REQUEST';
export const UPDATE_USERNAME = 'UPDATE_USERNAME';
export const UPDATE_USERNAME_REQUEST = 'UPDATE_USERNAME_REQUEST';
export const UPDATE_EMAIL = 'UPDATE_EMAIL';
export const UPDATE_EMAIL_REQUEST = 'UPDATE_EMAIL_REQUEST';
export const UPDATE_USER_DATA = 'UPDATE_USER_DATA';
export const UPDATE_USER_DATA_REQUEST = 'UPDATE_USER_DATA_REQUEST';
export const UPDATE_ACADEMIC_DATA = 'UPDATE_ACADEMIC_DATA';
export const UPDATE_ACADEMIC_DATA_REQUEST = 'UPDATE_ACADEMIC_DATA_REQUEST';
export const UPDATE_PROFILE_REQUEST = 'UPDATE_PROFILE_REQUEST';
export const BIO_VALIDATE = 'BIO_VALIDATE';

export const editProfileState: EditProfileState = {
  err: false,
  status: 'settled',
  data: {}
};
